package cn.edu.ubaa.ui.icons

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.vector.ImageVector

/** 一套风格统一的图标集。属性名与 Material 图标一一对应，便于调用点统一替换。 */
@Immutable
class AppIconSet(
    val Refresh: ImageVector,
    val CheckCircle: ImageVector,
    val ArrowBack: ImageVector,
    val Place: ImageVector,
    val Add: ImageVector,
    val Close: ImageVector,
    val Check: ImageVector,
    val Delete: ImageVector,
    val Tune: ImageVector,
    val DateRange: ImageVector,
    val Info: ImageVector,
    val Person: ImageVector,
    val Grade: ImageVector,
    val FilterList: ImageVector,
    val AssignmentTurnedIn: ImageVector,
    val School: ImageVector,
    val Paid: ImageVector,
    val History: ImageVector,
    val AccessTime: ImageVector,
    val Search: ImageVector,
    val Login: ImageVector,
    val Code: ImageVector,
    val Settings: ImageVector,
    val MeetingRoom: ImageVector,
    val AccountBalanceWallet: ImageVector,
    val Book: ImageVector,
    val Logout: ImageVector,
    val List: ImageVector,
    val KeyboardArrowLeft: ImageVector,
    val NetworkWifi: ImageVector,
    val EventSeat: ImageVector,
    val KeyboardArrowRight: ImageVector,
    val ArrowDropDown: ImageVector,
    val DirectionsRun: ImageVector,
    val ChevronRight: ImageVector,
    val Chair: ImageVector,
    val WbSunny: ImageVector,
    val LocationOn: ImageVector,
    val DirectionsBus: ImageVector,
    val Image: ImageVector,
    val CardGiftcard: ImageVector,
    val Share: ImageVector,
    val PhotoCamera: ImageVector,
    val Bolt: ImageVector,
    val Schedule: ImageVector,
    val MoreHoriz: ImageVector,
    val Assignment: ImageVector,
    val CalendarToday: ImageVector,
    val ExpandMore: ImageVector,
    val Business: ImageVector,
    val AssignmentInd: ImageVector,
    val EventBusy: ImageVector,
    val Map: ImageVector,
    val Event: ImageVector,
    val Category: ImageVector,
    val AccountCircle: ImageVector,
    val Home: ImageVector,
    val Menu: ImageVector,
    val SwapHoriz: ImageVector,
    val ExitToApp: ImageVector,
    val Lock: ImageVector,
    val AddCard: ImageVector,
    val Warning: ImageVector,
    val ExpandLess: ImageVector,
    val Error: ImageVector,
    val PlayArrow: ImageVector,
    val Phone: ImageVector,
    val Groups: ImageVector,
    val AccountBalance: ImageVector,
    val BarChart: ImageVector,
    val Label: ImageVector,
    val Clear: ImageVector,
    val QrCode: ImageVector,
    val Target: ImageVector,
)
